import { it } from "@effect/vitest";
import { AsyncLive } from "@zerospin/core/async/AsyncLive";
import { makeResourceDbConfig } from "@zerospin/core/drizzle/makeDbConfig";
import { makeMigratedInMemorySqljsDb } from "@zerospin/core/drizzle/makeMigratedInMemorySqljsDb";
import { makeSession } from "@zerospin/core/session/makeSession";
import { sessionRepoTables } from "@zerospin/core/session/sessionRepoTables";
import { DateTime, Effect, Either } from "effect";
import { describe, expect } from "vitest";

import { createPage, createSite } from "./contracts";
import { Page } from "./models/Page";
import { Site } from "./models/Site";
import { User } from "./models/User";
import { ownerFrontend } from "./ownerFrontend";

describe("site and page creation contracts", () => {
  it.effect("stages an autogenerated Site and its autogenerated initial Page", () =>
    Effect.gen(function* () {
      const actorId = "actr_site_contract_owner";
      const userId = "usr_site_contract_owner";
      const now = DateTime.toDateUtc(yield* DateTime.now);
      const dbConfig = makeResourceDbConfig({
        models: ownerFrontend.models,
        otherTables: sessionRepoTables,
      });
      const { schema } = dbConfig;
      const db = yield* makeMigratedInMemorySqljsDb({ dbConfig }).pipe(
        Effect.provide(AsyncLive),
      );

      db.insert(User.drizzleSchema)
        .values({
          id: userId,
          modelName: User.modelName,
          version: User.version,
          createdAt: now,
          updatedAt: now,
          actorId,
          clerkUserId: "site_contract_owner",
          username: null,
          displayName: null,
        })
        .run();

      const sessionId = "sesn_site_contract";
      const session = makeSession({
        frontend: ownerFrontend,
        generateSignature: () => Effect.succeed({ sessionToken: "test-session-token" }),
        sessionId,
      });
      session.store.setState({
        sessionId,
        accountId: "acct_1",
        accountName: ownerFrontend.accountName,
        actorId,
        generationId: "gen_site_contract",
        systemWorkerName: "site-contract-worker",
        systemVersion: "3.0.0",
        db,
        schema,
        models: ownerFrontend.models,
        vfsName: null,
        isInitialized: true,
        frontendIndex: null,
        lastRebasedPushedCursor: null,
      });

      const staged = yield* Effect.promise(() =>
        session.stageCommand({
          contractName: "createSite",
          payload: { userId },
        }),
      );

      expect(staged._tag).toBe("Right");
      if (staged._tag === "Left") {
        throw new Error(staged.left.message);
      }

      const siteRows = db.select().from(Site.drizzleSchema).all();

      expect(staged.right.version).toBe("1.1.0");
      expect(staged.right.payload.id).toMatch(/^sit_/);
      expect(staged.right.payload).toMatchObject({
        userId,
        slug: null,
        name: null,
        description: null,
      });
      expect(siteRows).toHaveLength(1);
      expect(siteRows[0]).toEqual(
        expect.objectContaining({
          id: staged.right.payload.id,
          version: "1.0.0",
          userId,
          slug: null,
          name: null,
          description: null,
        }),
      );

      const siteId = staged.right.payload.id;
      const stagedPage = yield* Effect.promise(() =>
        session.stageCommand({
          contractName: "createPage",
          payload: {
            siteId,
            slug: "home",
            pageType: "split-scroll",
          },
        }),
      );

      expect(stagedPage._tag).toBe("Right");
      if (stagedPage._tag === "Left") {
        throw new Error(stagedPage.left.message);
      }

      const pageRows = db.select().from(Page.drizzleSchema).all();

      expect(stagedPage.right.version).toBe("1.1.0");
      expect(stagedPage.right.payload.id).toMatch(/^pag_/);
      expect(stagedPage.right.payload).toMatchObject({
        siteId,
        slug: "home",
        title: null,
        description: null,
        pageType: "split-scroll",
      });
      expect(pageRows).toHaveLength(1);
      expect(pageRows[0]).toEqual(
        expect.objectContaining({
          id: stagedPage.right.payload.id,
          version: "1.0.0",
          siteId,
          slug: "home",
          title: null,
          description: null,
          pageType: "split-scroll",
        }),
      );
    }),
  );

  it.effect("rejects a payload that omits userId", () =>
    Effect.gen(function* () {
      const validation = yield* createSite
        .validatePayload({
          payload: {
            id: "sit_missing_user",
          },
        })
        .pipe(Effect.either);

      expect(Either.isLeft(validation)).toBe(true);
    }),
  );

  it.effect("rejects a Page payload that omits siteId", () =>
    Effect.gen(function* () {
      const validation = yield* createPage
        .validatePayload({
          payload: {
            id: "pag_missing_site",
            slug: "home",
            pageType: "split-scroll",
          },
        })
        .pipe(Effect.either);

      expect(Either.isLeft(validation)).toBe(true);
    }),
  );
});

describe("owner frontend creation guards", () => {
  it.effect("rejects a User that does not belong to the active actor", () =>
    Effect.gen(function* () {
      const userId = "usr_site_guard_owner";
      const now = DateTime.toDateUtc(yield* DateTime.now);
      const dbConfig = makeResourceDbConfig({
        models: ownerFrontend.models,
      });
      const db = yield* makeMigratedInMemorySqljsDb({ dbConfig }).pipe(
        Effect.provide(AsyncLive),
      );

      db.insert(User.drizzleSchema)
        .values({
          id: userId,
          modelName: User.modelName,
          version: User.version,
          createdAt: now,
          updatedAt: now,
          actorId: "actr_site_guard_owner",
          clerkUserId: "site_guard_owner",
          username: null,
          displayName: null,
        })
        .run();

      const [guard] = ownerFrontend.guards.createSite;
      if (guard === undefined) {
        throw new Error("Expected ownerFrontend createSite guard");
      }

      const error = yield* guard({
        actorId: "actr_different_site_owner",
        db,
        payload: {
          id: "sit_site_guard_owner",
          userId,
          slug: null,
          name: null,
          description: null,
        },
      }).pipe(Effect.flip);

      expect(error).toMatchObject({
        code: "create-site-owner-mismatch",
        status: 403,
      });
    }),
  );

  it.effect("rejects a Page whose Site does not belong to the active actor", () =>
    Effect.gen(function* () {
      const userId = "usr_page_guard_owner";
      const siteId = "sit_page_guard_owner";
      const now = DateTime.toDateUtc(yield* DateTime.now);
      const dbConfig = makeResourceDbConfig({
        models: ownerFrontend.models,
      });
      const db = yield* makeMigratedInMemorySqljsDb({ dbConfig }).pipe(
        Effect.provide(AsyncLive),
      );

      db.insert(User.drizzleSchema)
        .values({
          id: userId,
          modelName: User.modelName,
          version: User.version,
          createdAt: now,
          updatedAt: now,
          actorId: "actr_page_guard_owner",
          clerkUserId: "page_guard_owner",
          username: null,
          displayName: null,
        })
        .run();

      db.insert(Site.drizzleSchema)
        .values({
          id: siteId,
          modelName: Site.modelName,
          version: Site.version,
          createdAt: now,
          updatedAt: now,
          userId,
          slug: null,
          name: null,
          description: null,
        })
        .run();

      const [guard] = ownerFrontend.guards.createPage;
      if (guard === undefined) {
        throw new Error("Expected ownerFrontend createPage guard");
      }

      const error = yield* guard({
        actorId: "actr_different_page_owner",
        db,
        payload: {
          id: "pag_page_guard_owner",
          siteId,
          slug: "home",
          title: null,
          description: null,
          pageType: "split-scroll",
        },
      }).pipe(Effect.flip);

      expect(error).toMatchObject({
        code: "create-page-owner-mismatch",
        status: 403,
      });
    }),
  );
});
