import { expect, test } from "@playwright/test";

test("whole bricks move while the edit icon opens inspection", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("toolbar", { name: "Grid controls" }).getByRole("button", { name: "Bricks", exact: true }).click();
  const drawer = page.getByRole("dialog", { name: "Bricks", exact: true });
  await expect(drawer).toBeVisible();
  await expect(page.getByRole("group", { name: "Grid mode" })).toHaveCount(0);
  const grid = page.getByLabel("Brick grid");
  const canvas = grid.locator(".react-grid-layout");
  const source = drawer.locator('[data-group-representative="swatch/default"]');
  await source.dragTo(canvas, { targetPosition: { x: 20, y: 20 } });
  const brick = grid.locator("[data-brick-id]").first();
  await expect(brick).toBeVisible();
  const id = await brick.getAttribute("data-brick-id");
  const handle = brick;
  await handle.click();
  await expect(page).toHaveURL(/\/$/);
  const before = await brick.getAttribute("data-grid-x");
  const box = await handle.boundingBox();
  if (!box || before === null) throw new Error("Missing handle bounds or grid coordinate");
  await page.mouse.move(box.x + 16, box.y + 16);
  await page.mouse.down();
  await page.mouse.move(box.x + 176, box.y + 16, { steps: 10 });
  await page.mouse.up();
  await expect(brick).not.toHaveAttribute("data-grid-x", before);
  await expect(page).toHaveURL(/\/$/);
  const moved = await brick.getAttribute("data-grid-x");
  await brick.getByRole("link").focus();
  await page.keyboard.press("Enter");
  await expect(page).toHaveURL(new RegExp(`/groups/swatch/brick/${id}$`));
  await page.reload();
  await expect(brick).toHaveAttribute("data-grid-x", moved ?? "");
  await expect(brick.getByRole("link")).toBeVisible();
});
