import { createHash } from 'node:crypto';
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(scriptDir, '..');
const migrationsRoot = path.join(packageRoot, 'src/SharedWorker/drizzle/user');
const outputPath = path.join(migrationsRoot, 'migrations.ts');
const migrationFolders = existsSync(migrationsRoot)
  ? readdirSync(migrationsRoot, { withFileTypes: true })
      .filter(entry => entry.isDirectory())
      .map(entry => entry.name)
      .filter(name =>
        existsSync(path.join(migrationsRoot, name, 'migration.sql')),
      )
      .sort()
  : [];
const migrations = [];

for (const name of migrationFolders) {
  const migrationPath = path.join(migrationsRoot, name, 'migration.sql');
  const migrationSql = readFileSync(migrationPath, 'utf8');
  const timestamp = name.match(/^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/);
  const createdAt =
    timestamp === null
      ? migrations.length
      : Date.UTC(
          Number(timestamp[1]),
          Number(timestamp[2]) - 1,
          Number(timestamp[3]),
          Number(timestamp[4]),
          Number(timestamp[5]),
          Number(timestamp[6]),
        );
  migrations.push({
    name,
    hash: createHash('sha256').update(migrationSql).digest('hex'),
    createdAt,
    sql: migrationSql
      .split('--> statement-breakpoint')
      .map(statement => statement.trim())
      .filter(statement => statement.length > 0),
  });
}

mkdirSync(migrationsRoot, { recursive: true });
writeFileSync(
  outputPath,
  [
    '/* Generated by scripts/writeUserMigrationManifest.mjs. */',
    `export const userMigrations = ${JSON.stringify(migrations, null, 2)};`,
    '',
  ].join('\n'),
);
