import { expect, test } from "@playwright/test";

test("Inspect opens details and Arrange moves bricks without navigation", async ({ page }) => {
  await page.goto("/");
  const grid = page.getByLabel("Brick grid");
  const inspect = page.getByRole("banner").getByRole("button", { name: "Inspect", exact: true });
  const arrange = page.getByRole("banner").getByRole("button", { name: "Arrange", exact: true });
  await expect(inspect).toHaveAttribute("aria-pressed", "true");
  const canvas = grid.locator(".react-grid-layout");
  const source = page.locator('[data-collection-representative="swatch/default/2x2"]');
  await source.dragTo(canvas, { targetPosition: { x: 20, y: 20 } });
  const brick = grid.locator("[data-brick-id]").first();
  await expect(brick).toBeVisible();
  const id = await brick.getAttribute("data-brick-id");
  const link = brick.getByRole("link");
  await expect(brick.locator("[inert]")).toHaveCount(1);
  const before = await brick.getAttribute("data-grid-x");
  if (before === null) throw new Error("Missing grid coordinate");
  const box = await brick.boundingBox();
  if (!box) throw new Error("Missing brick bounds");
  await page.mouse.move(box.x + 20, box.y + 20);
  await page.mouse.down();
  await page.mouse.move(box.x + 180, box.y + 20, { steps: 10 });
  await page.mouse.up();
  await expect(brick).toHaveAttribute("data-grid-x", before);
  await link.focus();
  await page.keyboard.press("Enter");
  await expect(page).toHaveURL(new RegExp(`/collections/swatch/brick/${id}$`));
  await expect(page.getByTestId("brick-detail-pane")).toBeVisible();
  await expect(inspect).toHaveAttribute("aria-pressed", "true");
  await arrange.click();
  await expect(brick.getByRole("link")).toHaveCount(0);
  const arrangedBox = await brick.boundingBox();
  if (!arrangedBox) throw new Error("Missing arranged brick bounds");
  await page.mouse.move(arrangedBox.x + 20, arrangedBox.y + 20);
  await page.mouse.down();
  await page.mouse.move(arrangedBox.x + 180, arrangedBox.y + 20, { steps: 10 });
  await page.mouse.up();
  await expect(brick).not.toHaveAttribute("data-grid-x", before);
  await expect(page).toHaveURL(new RegExp(`/collections/swatch/brick/${id}$`));
  await brick.click();
  await expect(page).toHaveURL(new RegExp(`/collections/swatch/brick/${id}$`));
  await page.getByRole("link", { name: "Brick collections", exact: true }).click();
  await expect(arrange).toHaveAttribute("aria-pressed", "true");
  await page.locator('[data-collection-representative="swatch/default/2x2"]').dragTo(canvas, { targetPosition: { x: 180, y: 20 } });
  await expect(grid.locator("[data-brick-id]")).toHaveCount(2);
  await expect(arrange).toHaveAttribute("aria-pressed", "true");
  await page.reload();
  await expect(inspect).toHaveAttribute("aria-pressed", "true");
  await expect(grid.locator("[data-brick-id]")).toHaveCount(2);
  await grid.locator("[data-brick-id]").first().click();
  await expect(page.getByTestId("brick-detail-pane")).toBeVisible();
});
