import { primitives } from '@zerospin/schema';
import { Effect, type Schema } from 'effect';
import { assert, type Equals } from 'tsafe';

import { makeModel } from './makeModel.ts';
import { makeReplica } from './makeReplica.ts';
import type { InferResource } from './types.ts';

const User = makeModel(
  {
    abbreviation: 'usr',
    modelName: 'user',
    attributes: {
      name: primitives.text(),
    },
    indexes: [],
    version: '1.0.0',
  },
  [],
);

makeModel(
  {
    abbreviation: 'xid',
    modelName: 'withAutogeneratedAttribute',
    attributes: {
      // @ts-expect-error CoreTypeError — autogeneration belongs to payload identities
      otherId: User.primaryKey({ autogenerate: true }),
    },
    indexes: [],
    version: '1.0.0',
  },
  [],
);

const Todo = makeModel(
  {
    abbreviation: 'todo',
    modelName: 'todo',
    attributes: {
      title: primitives.text(),
      completed: primitives.boolean(),
    },
    indexes: [],
    version: '2.0.0',
  },
  [
    {
      abbreviation: 'todo',
      modelName: 'todo',
      attributes: {
        title: primitives.text(),
      },
      indexes: [],
      version: '1.0.0',
      adaptResource: ({ resource }) =>
        Effect.succeed({
          id: resource.id,
          modelName: resource.modelName,
          createdAt: resource.createdAt,
          updatedAt: resource.updatedAt,
          version: '1.0.0',
          title: resource.title,
        }),
    },
  ],
);

declare const currentTodoResource: InferResource<typeof Todo>;
assert<
  Equals<
    Pick<typeof currentTodoResource, 'title' | 'completed'>,
    { title: string; completed: boolean }
  >
>();
assert<
  Equals<
    'deletedAt' extends keyof typeof currentTodoResource ? true : false,
    false
  >
>();
const historicalTodoResource = Todo.adaptResource({
  version: '1.0.0',
  resource: currentTodoResource,
});
assert<
  Equals<Effect.Success<typeof historicalTodoResource>['title'], string>
>();
assert<
  Equals<
    'completed' extends keyof Effect.Success<typeof historicalTodoResource>
      ? true
      : false,
    false
  >
>();
assert<
  Equals<
    'deletedAt' extends keyof Effect.Success<typeof historicalTodoResource>
      ? true
      : false,
    false
  >
>();

const TodoReplica = makeReplica({
  sourceModel: Todo,
  serviceName: 'todos',
});
assert<Equals<typeof TodoReplica.sourceModel, typeof Todo>>();
assert<Equals<typeof TodoReplica.serviceName, 'todos'>>();

declare const currentTodoReplicaResource: InferResource<typeof TodoReplica>;
assert<
  Equals<
    Pick<
      typeof currentTodoReplicaResource,
      'title' | 'completed' | 'deletedAt'
    >,
    { title: string; completed: boolean; deletedAt: Date | null }
  >
>();
const historicalTodoReplicaResource = TodoReplica.adaptResource({
  version: '1.0.0',
  resource: currentTodoReplicaResource,
});
assert<
  Equals<
    Effect.Success<typeof historicalTodoReplicaResource>['title'],
    string
  >
>();
assert<
  Equals<
    Effect.Success<typeof historicalTodoReplicaResource>['deletedAt'],
    Date | null
  >
>();
assert<
  Equals<
    'completed' extends keyof Effect.Success<
      typeof historicalTodoReplicaResource
    >
      ? true
      : false,
    false
  >
>();

TodoReplica.replicateResource('2.0.0', {
  resource: {
    id: 'todo_replication_input',
    modelName: 'todo',
    createdAt: new Date(),
    updatedAt: new Date(),
    version: '2.0.0',
    title: 'Replication input',
    completed: false,
    // @ts-expect-error live replication accepts the authoritative resource, not replica deletion state
    deletedAt: null,
  },
});

TodoReplica.replicateResource('1.0.0', {
  resource: {
    id: 'todo_historical_replication_input',
    modelName: 'todo',
    createdAt: new Date(),
    updatedAt: new Date(),
    version: '1.0.0',
    title: 'Historical replication input',
    // @ts-expect-error historical replication also accepts the authoritative resource, not replica deletion state
    deletedAt: null,
  },
});

const historicalCreateSchema = Todo.createMutation('1.0.0');
assert<
  Equals<
    Schema.Schema.Type<
      typeof historicalCreateSchema
    >['operation']['attributes'],
    { readonly title: string }
  >
>();
assert<
  Equals<
    Schema.Codec.Encoded<typeof historicalCreateSchema>['modelVersion'],
    '1.0.0'
  >
>();

const currentCreateSchema = Todo.createMutation('2.0.0');
assert<
  Equals<
    Schema.Schema.Type<typeof currentCreateSchema>['operation']['attributes'],
    { title: string; completed: boolean }
  >
>();

Todo.create('1.0.0', {
  resourceId: 'todo_historical',
  attributes: { title: 'Historical' },
});

Todo.create('2.0.0', {
  resourceId: 'todo_current',
  attributes: { title: 'Current', completed: false },
});

// @ts-expect-error model operation versions must be declared by the model
Todo.createMutation('9.0.0');

Todo.create('2.0.0', {
  resourceId: 'todo_missing_current_attribute',
  // @ts-expect-error current model create requires every current attribute
  attributes: { title: 'Missing completed' },
});

Todo.create('1.0.0', {
  resourceId: 'todo_extra_historical_attribute',
  attributes: {
    title: 'Historical',
    // @ts-expect-error historical model inference excludes current-only attributes
    completed: false,
  },
});

makeModel(
  {
    abbreviation: 'xpk',
    modelName: 'withExtraPrimaryKey',
    attributes: {
      // @ts-expect-error CoreTypeError — makeModel synthesizes the only primary key
      versionName: primitives.primaryKey({ abbreviation: 'vrsn' }),
    },
    indexes: [],
    version: '1.0.0',
  },
  [],
);
