import type { LayoutItem } from "react-grid-layout";

import type { ICollectionTileDef } from "@/components/home/tiles/types";

export type ILayoutItem = LayoutItem & { def: ICollectionTileDef };
export type ILayout = ILayoutItem[];

/** Mirrors grid seed shape: 14× 2×2 art row, then 46× full-width 4×1 rows (`gridState` / `useGridStore`). */
export const seedLayout: ILayout = [
  {
    i: "orange-flag--0",
    x: 0,
    y: 0,
    w: 2,
    h: 2,
    def: {
      name: "2x2",
      w: 2,
      h: 2,
      label: "Orange flag",
      collectionId: "orange-flag",
      collectionLabel: "Orange flag",
      popular: "4x1",
    },
  },
  {
    i: "black-circle--1",
    x: 2,
    y: 0,
    w: 2,
    h: 2,
    def: {
      name: "2x2",
      w: 2,
      h: 2,
      label: "Black circle",
      collectionId: "black-circle",
      collectionLabel: "Black circle",
      popular: "1x1",
    },
  },
  {
    i: "green-arch--2",
    x: 0,
    y: 2,
    w: 2,
    h: 2,
    def: {
      name: "2x2",
      w: 2,
      h: 2,
      label: "Green arch",
      collectionId: "green-arch",
      collectionLabel: "Green arch",
      popular: "1x1",
    },
  },
  {
    i: "blue-grid--3",
    x: 2,
    y: 2,
    w: 2,
    h: 2,
    def: {
      name: "2x2",
      w: 2,
      h: 2,
      label: "Blue grid",
      collectionId: "blue-grid",
      collectionLabel: "Blue grid",
      popular: "4x1",
    },
  },
  {
    i: "cream-bench--4",
    x: 0,
    y: 4,
    w: 2,
    h: 2,
    def: {
      name: "2x2",
      w: 2,
      h: 2,
      label: "Cream bench",
      collectionId: "cream-bench",
      collectionLabel: "Cream bench",
      popular: "1x1",
    },
  },
  {
    i: "green-g-logo--5",
    x: 2,
    y: 4,
    w: 2,
    h: 2,
    def: {
      name: "2x2",
      w: 2,
      h: 2,
      label: "Green G",
      collectionId: "green-g-logo",
      collectionLabel: "Green G",
      popular: "4x1",
    },
  },
  {
    i: "cream-square--6",
    x: 0,
    y: 6,
    w: 2,
    h: 2,
    def: {
      name: "2x2",
      w: 2,
      h: 2,
      label: "Cream square",
      collectionId: "cream-square",
      collectionLabel: "Cream square",
      popular: "1x1",
    },
  },
  {
    i: "pink-dots--7",
    x: 2,
    y: 6,
    w: 2,
    h: 2,
    def: {
      name: "2x2",
      w: 2,
      h: 2,
      label: "Pink dots",
      collectionId: "pink-dots",
      collectionLabel: "Pink dots",
      popular: "4x1",
    },
  },
  {
    i: "black-m-logo--8",
    x: 0,
    y: 8,
    w: 2,
    h: 2,
    def: {
      name: "2x2",
      w: 2,
      h: 2,
      label: "Black M",
      collectionId: "black-m-logo",
      collectionLabel: "Black M",
      popular: "1x1",
    },
  },
  {
    i: "orange-block--9",
    x: 2,
    y: 8,
    w: 2,
    h: 2,
    def: {
      name: "2x2",
      w: 2,
      h: 2,
      label: "Orange blocks",
      collectionId: "orange-block",
      collectionLabel: "Orange blocks",
      popular: "4x1",
    },
  },
  {
    i: "purple-lines--10",
    x: 0,
    y: 10,
    w: 2,
    h: 2,
    def: {
      name: "2x2",
      w: 2,
      h: 2,
      label: "Purple lines",
      collectionId: "purple-lines",
      collectionLabel: "Purple lines",
      popular: "1x1",
    },
  },
  {
    i: "pink-asterisk--11",
    x: 2,
    y: 10,
    w: 2,
    h: 2,
    def: {
      name: "2x2",
      w: 2,
      h: 2,
      label: "Pink asterisk",
      collectionId: "pink-asterisk",
      collectionLabel: "Pink asterisk",
      popular: "4x1",
    },
  },
  {
    i: "green-empty--12",
    x: 0,
    y: 12,
    w: 2,
    h: 2,
    def: {
      name: "2x2",
      w: 2,
      h: 2,
      label: "Green empty",
      collectionId: "green-empty",
      collectionLabel: "Green empty",
      popular: "2x2",
    },
  },
  {
    i: "green-cross--13",
    x: 2,
    y: 12,
    w: 2,
    h: 2,
    def: {
      name: "2x2",
      w: 2,
      h: 2,
      label: "Green cross",
      collectionId: "green-cross",
      collectionLabel: "Green cross",
      popular: "1x1",
    },
  },
  { i: "text-tile-work--0", x: 0, y: 14, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--1", x: 0, y: 15, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--2", x: 0, y: 16, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--3", x: 0, y: 17, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--4", x: 0, y: 18, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--5", x: 0, y: 19, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--6", x: 0, y: 20, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--7", x: 0, y: 21, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--8", x: 0, y: 22, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--9", x: 0, y: 23, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--10", x: 0, y: 24, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--11", x: 0, y: 25, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--12", x: 0, y: 26, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--13", x: 0, y: 27, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--14", x: 0, y: 28, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--15", x: 0, y: 29, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--16", x: 0, y: 30, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--17", x: 0, y: 31, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--18", x: 0, y: 32, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--19", x: 0, y: 33, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--20", x: 0, y: 34, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--21", x: 0, y: 35, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--22", x: 0, y: 36, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--23", x: 0, y: 37, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--24", x: 0, y: 38, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--25", x: 0, y: 39, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--26", x: 0, y: 40, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--27", x: 0, y: 41, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--28", x: 0, y: 42, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--29", x: 0, y: 43, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--30", x: 0, y: 44, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--31", x: 0, y: 45, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--32", x: 0, y: 46, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--33", x: 0, y: 47, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--34", x: 0, y: 48, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--35", x: 0, y: 49, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--36", x: 0, y: 50, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--37", x: 0, y: 51, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--38", x: 0, y: 52, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--39", x: 0, y: 53, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--40", x: 0, y: 54, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--41", x: 0, y: 55, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--42", x: 0, y: 56, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--43", x: 0, y: 57, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--44", x: 0, y: 58, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
  { i: "text-tile-work--45", x: 0, y: 59, w: 4, h: 1, def: { name: "4x1", w: 4, h: 1, label: "Text tile", collectionId: "text-tile", collectionLabel: "Text tile", popular: "4x1" } },
];
