/* Generated by scripts/writeUserMigrationManifest.mjs. */
export const userMigrations = [
  {
    name: '20260707224326_cute_dagger',
    hash: '1e502b156595d45ca82f4fa5bfda853f039965e25a8e14918bb9f79a15c5f169',
    createdAt: 1783464206000,
    sql: [
      'CREATE TABLE `replicas` (\n\t`id` text PRIMARY KEY,\n\t`accountId` text NOT NULL,\n\t`accountName` text NOT NULL,\n\t`actorId` text NOT NULL,\n\t`actorName` text NOT NULL,\n\t`frontendName` text NOT NULL,\n\t`frontendVersion` text NOT NULL,\n\t`databaseName` text NOT NULL\n);',
      'CREATE UNIQUE INDEX `replicas_actor_frontend_version_idx` ON `replicas` (`actorId`,`frontendName`,`frontendVersion`);',
      'CREATE INDEX `replicas_frontend_idx` ON `replicas` (`frontendName`);',
    ],
  },
];
