/* Never use an array to make any of this shit easy. */

import type { LayoutItem } from "react-grid-layout";

import { collectionsHash, type ICollectionBrickDef } from "@qrk.sh/bricks";

const swatchCollection = collectionsHash.swatch;
const iconCollection = collectionsHash.icon;
const textBrickCollection = collectionsHash.text;

export type ILayoutItem = LayoutItem & { def: ICollectionBrickDef };
export type ILayout = ILayoutItem[];

/** Homepage grid: 14× 4×4 art row, then 46× full-width 8×2 text rows (`useGridLayoutStore` initial state). */
export const seedLayout: ILayout = [
  {
    i: "icon--11",
    x: 4,
    y: 20,
    w: 4,
    h: 4,
    def: iconCollection.variants.default.sizes["4x4"].def,
  },
  {
    i: "swatch--12",
    x: 0,
    y: 24,
    w: 4,
    h: 4,
    def: swatchCollection.variants.default.sizes["4x4"].def,
  },
  {
    i: "text-brick-work--0",
    x: 0,
    y: 28,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--1",
    x: 0,
    y: 30,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--2",
    x: 0,
    y: 32,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--3",
    x: 0,
    y: 34,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--4",
    x: 0,
    y: 36,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--5",
    x: 0,
    y: 38,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--6",
    x: 0,
    y: 40,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--7",
    x: 0,
    y: 42,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--8",
    x: 0,
    y: 44,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--9",
    x: 0,
    y: 46,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--10",
    x: 0,
    y: 48,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--11",
    x: 0,
    y: 50,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--12",
    x: 0,
    y: 52,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--13",
    x: 0,
    y: 54,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--14",
    x: 0,
    y: 56,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--15",
    x: 0,
    y: 58,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--16",
    x: 0,
    y: 60,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--17",
    x: 0,
    y: 62,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--18",
    x: 0,
    y: 64,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--19",
    x: 0,
    y: 66,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--20",
    x: 0,
    y: 68,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--21",
    x: 0,
    y: 70,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--22",
    x: 0,
    y: 72,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--23",
    x: 0,
    y: 74,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--24",
    x: 0,
    y: 76,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--25",
    x: 0,
    y: 78,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--26",
    x: 0,
    y: 80,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--27",
    x: 0,
    y: 82,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--28",
    x: 0,
    y: 84,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--29",
    x: 0,
    y: 86,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--30",
    x: 0,
    y: 88,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--31",
    x: 0,
    y: 90,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--32",
    x: 0,
    y: 92,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--33",
    x: 0,
    y: 94,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--34",
    x: 0,
    y: 96,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--35",
    x: 0,
    y: 98,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--36",
    x: 0,
    y: 100,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--37",
    x: 0,
    y: 102,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--38",
    x: 0,
    y: 104,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--39",
    x: 0,
    y: 106,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--40",
    x: 0,
    y: 108,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--41",
    x: 0,
    y: 110,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--42",
    x: 0,
    y: 112,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--43",
    x: 0,
    y: 114,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--44",
    x: 0,
    y: 116,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
  {
    i: "text-brick-work--45",
    x: 0,
    y: 118,
    w: 8,
    h: 2,
    def: textBrickCollection.variants.default.sizes["8x2"].def,
  },
];
