/* Generated by scripts/writeUserReplicaMigrationManifest.mjs. */
export const userReplicaMigrations = [
  {
    name: '20260811011400_user_replica_v1',
    hash: 'a29d27894bd90a37a13146af5727cce50e95bc1f2bae24e9feebe3609ce3a8a5',
    createdAt: 1786410840000,
    sql: [
      'CREATE TABLE `aggregateFrontendReplicas` (\n\t`id` text PRIMARY KEY,\n\t`aggregateId` text NOT NULL,\n\t`aggregateName` text NOT NULL,\n\t`userId` text NOT NULL,\n\t`frontendName` text NOT NULL,\n\t`aggregateFrontendLockKey` text NOT NULL,\n\t`aggregateFrontendLock` text NOT NULL,\n\t`frontendSpec` text NOT NULL,\n\t`databaseName` text NOT NULL,\n\t`createdAt` integer NOT NULL\n);',
      'CREATE TABLE `serviceFrontendReplicas` (\n\t`id` text PRIMARY KEY,\n\t`serviceName` text NOT NULL,\n\t`userId` text NOT NULL,\n\t`frontendName` text NOT NULL,\n\t`serviceFrontendLockKey` text NOT NULL,\n\t`serviceFrontendLock` text NOT NULL,\n\t`frontendSpec` text NOT NULL,\n\t`databaseName` text NOT NULL,\n\t`createdAt` integer NOT NULL\n);',
      'CREATE UNIQUE INDEX `aggregate_frontend_replicas_target_lock_idx` ON `aggregateFrontendReplicas` (`aggregateId`,`aggregateName`,`userId`,`frontendName`,`aggregateFrontendLockKey`);',
      'CREATE UNIQUE INDEX `service_frontend_replicas_target_lock_idx` ON `serviceFrontendReplicas` (`serviceName`,`userId`,`frontendName`,`serviceFrontendLockKey`);',
    ],
  },
];
